# coding: utf-8

"""
VAM-Data-Bridges

API Documentation of the **DataBridges** platform: https://databridges.vam.wfp.org/. For API discussions and details: #api-integration-vam-data-bridges on Slack, [Teams channel](https://teams.microsoft.com/l/team/19%3a4ca595f7681f4ffa8a86b7af58832e8d%40thread.skype/conversations?groupId=cbd1e508-c6e8-459d-96b7-6cac3039c42c&tenantId=462ad9ae-d7d9-4206-b874-71b1e079776f) **API Integration** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern

The version of the OpenAPI document: 7.0.0
Contact: wfp.economicanalysis@wfp.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from pydantic_core import to_jsonable_python
from typing_extensions import Self


class CariAdm1ValuesDTO(BaseModel):
    """
    CariAdm1ValuesDTO
    """  # noqa: E501

    survey_id: Optional[StrictInt] = Field(default=None, alias="surveyID")
    survey_name: Optional[StrictStr] = Field(default=None, alias="surveyName")
    cari_methodology_name: Optional[StrictStr] = Field(
        default=None, alias="cariMethodologyName"
    )
    fcs_methodology_name: Optional[StrictStr] = Field(
        default=None, alias="fcsMethodologyName"
    )
    additional_survey_metadata: Optional[StrictStr] = Field(
        default=None, alias="additionalSurveyMetadata"
    )
    adm0_code: Optional[StrictInt] = Field(default=None, alias="adm0Code")
    adm0_name: Optional[StrictStr] = Field(default=None, alias="adm0Name")
    cari_indicator_id: Optional[StrictInt] = Field(
        default=None, alias="cariIndicatorID"
    )
    cari_indicator_name: Optional[StrictStr] = Field(
        default=None, alias="cariIndicatorName"
    )
    cari_indicator_category_id: Optional[StrictInt] = Field(
        default=None, alias="cariIndicatorCategoryID"
    )
    indicator_category_label: Optional[StrictStr] = Field(
        default=None, alias="indicatorCategoryLabel"
    )
    adm1_code: Optional[StrictInt] = Field(default=None, alias="adm1Code")
    adm1_name: Optional[StrictStr] = Field(default=None, alias="adm1Name")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "surveyID",
        "surveyName",
        "cariMethodologyName",
        "fcsMethodologyName",
        "additionalSurveyMetadata",
        "adm0Code",
        "adm0Name",
        "cariIndicatorID",
        "cariIndicatorName",
        "cariIndicatorCategoryID",
        "indicatorCategoryLabel",
        "adm1Code",
        "adm1Name",
    ]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CariAdm1ValuesDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if survey_name (nullable) is None
        # and model_fields_set contains the field
        if self.survey_name is None and "survey_name" in self.model_fields_set:
            _dict["surveyName"] = None

        # set to None if cari_methodology_name (nullable) is None
        # and model_fields_set contains the field
        if (
            self.cari_methodology_name is None
            and "cari_methodology_name" in self.model_fields_set
        ):
            _dict["cariMethodologyName"] = None

        # set to None if fcs_methodology_name (nullable) is None
        # and model_fields_set contains the field
        if (
            self.fcs_methodology_name is None
            and "fcs_methodology_name" in self.model_fields_set
        ):
            _dict["fcsMethodologyName"] = None

        # set to None if additional_survey_metadata (nullable) is None
        # and model_fields_set contains the field
        if (
            self.additional_survey_metadata is None
            and "additional_survey_metadata" in self.model_fields_set
        ):
            _dict["additionalSurveyMetadata"] = None

        # set to None if adm0_code (nullable) is None
        # and model_fields_set contains the field
        if self.adm0_code is None and "adm0_code" in self.model_fields_set:
            _dict["adm0Code"] = None

        # set to None if adm0_name (nullable) is None
        # and model_fields_set contains the field
        if self.adm0_name is None and "adm0_name" in self.model_fields_set:
            _dict["adm0Name"] = None

        # set to None if cari_indicator_name (nullable) is None
        # and model_fields_set contains the field
        if (
            self.cari_indicator_name is None
            and "cari_indicator_name" in self.model_fields_set
        ):
            _dict["cariIndicatorName"] = None

        # set to None if indicator_category_label (nullable) is None
        # and model_fields_set contains the field
        if (
            self.indicator_category_label is None
            and "indicator_category_label" in self.model_fields_set
        ):
            _dict["indicatorCategoryLabel"] = None

        # set to None if adm1_code (nullable) is None
        # and model_fields_set contains the field
        if self.adm1_code is None and "adm1_code" in self.model_fields_set:
            _dict["adm1Code"] = None

        # set to None if adm1_name (nullable) is None
        # and model_fields_set contains the field
        if self.adm1_name is None and "adm1_name" in self.model_fields_set:
            _dict["adm1Name"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CariAdm1ValuesDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "surveyID": obj.get("surveyID"),
                "surveyName": obj.get("surveyName"),
                "cariMethodologyName": obj.get("cariMethodologyName"),
                "fcsMethodologyName": obj.get("fcsMethodologyName"),
                "additionalSurveyMetadata": obj.get("additionalSurveyMetadata"),
                "adm0Code": obj.get("adm0Code"),
                "adm0Name": obj.get("adm0Name"),
                "cariIndicatorID": obj.get("cariIndicatorID"),
                "cariIndicatorName": obj.get("cariIndicatorName"),
                "cariIndicatorCategoryID": obj.get("cariIndicatorCategoryID"),
                "indicatorCategoryLabel": obj.get("indicatorCategoryLabel"),
                "adm1Code": obj.get("adm1Code"),
                "adm1Name": obj.get("adm1Name"),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
