# coding: utf-8

"""
VAMDataBridges

API Documentation of the **DataBridges** platform: https://databridges.vam.wfp.org/. For API discussions and details: #api-integration-vam-data-bridges on Slack, [Teams channel](https://teams.microsoft.com/l/team/19%3a4ca595f7681f4ffa8a86b7af58832e8d%40thread.skype/conversations?groupId=cbd1e508-c6e8-459d-96b7-6cac3039c42c&tenantId=462ad9ae-d7d9-4206-b874-71b1e079776f) **API Integration** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern

The version of the OpenAPI document: v2
Contact: wfp.economicanalysis@wfp.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from pydantic_core import to_jsonable_python
from typing_extensions import Self

from data_bridges_client.models.list_item_dto import ListItemDto


class HungerHotSpotDataDTO(BaseModel):
    """
    HungerHotSpotDataDTO
    """  # noqa: E501

    iso3_code: Optional[StrictStr] = Field(default=None, alias="iso3Code")
    hunger_hotspots_date: Optional[datetime] = Field(
        default=None, alias="hungerHotspotsDate"
    )
    category: Optional[ListItemDto] = None
    indicators: Optional[List[ListItemDto]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "iso3Code",
        "hungerHotspotsDate",
        "category",
        "indicators",
    ]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HungerHotSpotDataDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of category
        if self.category:
            _dict["category"] = self.category.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in indicators (list)
        _items = []
        if self.indicators:
            for _item_indicators in self.indicators:
                if _item_indicators:
                    _items.append(_item_indicators.to_dict())
            _dict["indicators"] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if iso3_code (nullable) is None
        # and model_fields_set contains the field
        if self.iso3_code is None and "iso3_code" in self.model_fields_set:
            _dict["iso3Code"] = None

        # set to None if indicators (nullable) is None
        # and model_fields_set contains the field
        if self.indicators is None and "indicators" in self.model_fields_set:
            _dict["indicators"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HungerHotSpotDataDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "iso3Code": obj.get("iso3Code"),
                "hungerHotspotsDate": obj.get("hungerHotspotsDate"),
                "category": (
                    ListItemDto.from_dict(obj["category"])
                    if obj.get("category") is not None
                    else None
                ),
                "indicators": (
                    [ListItemDto.from_dict(_item) for _item in obj["indicators"]]
                    if obj.get("indicators") is not None
                    else None
                ),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
