# coding: utf-8

"""
    VAM-Data-Bridges

    API Documentation of the **DataBridges** platform: https://databridges.vam.wfp.org/. For API discussions and details: #api-integration-vam-data-bridges on Slack, [Teams channel](https://teams.microsoft.com/l/team/19%3a4ca595f7681f4ffa8a86b7af58832e8d%40thread.skype/conversations?groupId=cbd1e508-c6e8-459d-96b7-6cac3039c42c&tenantId=462ad9ae-d7d9-4206-b874-71b1e079776f) **API Integration** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern

    The version of the OpenAPI document: 7.0.0
    Contact: wfp.economicanalysis@wfp.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class IpcHistoricalDatumDto(BaseModel):
    """
    IpcHistoricalDatumDto
    """ # noqa: E501
    analysis_id: Optional[StrictInt] = Field(default=None, alias="analysisId")
    analysis_title: Optional[StrictStr] = Field(default=None, alias="analysisTitle")
    iso3_alpha3: Optional[StrictStr] = Field(default=None, alias="iso3Alpha3")
    country_name: Optional[StrictStr] = Field(default=None, alias="countryName")
    analysis_date: Optional[datetime] = Field(default=None, alias="analysisDate")
    start_date_current_period: Optional[datetime] = Field(default=None, alias="StartDate_CurrentPeriod")
    end_date_current_period: Optional[datetime] = Field(default=None, alias="EndDate_CurrentPeriod")
    start_date_projected_period: Optional[datetime] = Field(default=None, alias="StartDate_ProjectedPeriod")
    end_date_projected_period: Optional[datetime] = Field(default=None, alias="EndDate_ProjectedPeriod")
    start_date_second_projected_period: Optional[datetime] = Field(default=None, alias="StartDate_SecondProjectedPeriod")
    end_date_second_projected_period: Optional[datetime] = Field(default=None, alias="EndDate_SecondProjectedPeriod")
    population: Optional[Union[StrictFloat, StrictInt]] = None
    population_percentage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="populationPercentage")
    phase3_plus_population: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase3PlusPopulation")
    phase3_plus_percentage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase3PlusPercentage")
    estimated_population: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="estimatedPopulation")
    phase1_population: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase1Population")
    phase1_percentage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase1Percentage")
    phase2_population: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase2Population")
    phase2_percentage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase2Percentage")
    phase3_population: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase3Population")
    phase3_percentage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase3Percentage")
    phase4_population: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase4Population")
    phase4_percentage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase4Percentage")
    phase5_population: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase5Population")
    phase5_percentage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase5Percentage")
    phase3_plus_population_projected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase3PlusPopulationProjected")
    phase3_plus_percentage_projected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase3PlusPercentageProjected")
    estimated_population_projected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="estimatedPopulationProjected")
    phase1_population_projected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase1PopulationProjected")
    phase1_percentage_projected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase1PercentageProjected")
    phase2_population_projected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase2PopulationProjected")
    phase2_percentage_projected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase2PercentageProjected")
    phase3_population_projected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase3PopulationProjected")
    phase3_percentage_projected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase3PercentageProjected")
    phase4_population_projected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase4PopulationProjected")
    phase4_percentage_projected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase4PercentageProjected")
    phase5_population_projected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase5PopulationProjected")
    phase5_percentage_projected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase5PercentageProjected")
    phase3_plus_population_second_projected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase3PlusPopulationSecondProjected")
    phase3_plus_percentage_second_projected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase3PlusPercentageSecondProjected")
    estimated_population_second_projected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="estimatedPopulationSecondProjected")
    phase1_population_second_projected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase1PopulationSecondProjected")
    phase1_percentage_second_projected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase1PercentageSecondProjected")
    phase2_population_second_projected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase2PopulationSecondProjected")
    phase2_percentage_second_projected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase2PercentageSecondProjected")
    phase3_population_second_projected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase3PopulationSecondProjected")
    phase3_percentage_second_projected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase3PercentageSecondProjected")
    phase4_population_second_projected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase4PopulationSecondProjected")
    phase4_percentage_second_projected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase4PercentageSecondProjected")
    phase5_population_second_projected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase5PopulationSecondProjected")
    phase5_percentage_second_projected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase5PercentageSecondProjected")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["analysisId", "analysisTitle", "iso3Alpha3", "countryName", "analysisDate", "StartDate_CurrentPeriod", "EndDate_CurrentPeriod", "StartDate_ProjectedPeriod", "EndDate_ProjectedPeriod", "StartDate_SecondProjectedPeriod", "EndDate_SecondProjectedPeriod", "population", "populationPercentage", "phase3PlusPopulation", "phase3PlusPercentage", "estimatedPopulation", "phase1Population", "phase1Percentage", "phase2Population", "phase2Percentage", "phase3Population", "phase3Percentage", "phase4Population", "phase4Percentage", "phase5Population", "phase5Percentage", "phase3PlusPopulationProjected", "phase3PlusPercentageProjected", "estimatedPopulationProjected", "phase1PopulationProjected", "phase1PercentageProjected", "phase2PopulationProjected", "phase2PercentageProjected", "phase3PopulationProjected", "phase3PercentageProjected", "phase4PopulationProjected", "phase4PercentageProjected", "phase5PopulationProjected", "phase5PercentageProjected", "phase3PlusPopulationSecondProjected", "phase3PlusPercentageSecondProjected", "estimatedPopulationSecondProjected", "phase1PopulationSecondProjected", "phase1PercentageSecondProjected", "phase2PopulationSecondProjected", "phase2PercentageSecondProjected", "phase3PopulationSecondProjected", "phase3PercentageSecondProjected", "phase4PopulationSecondProjected", "phase4PercentageSecondProjected", "phase5PopulationSecondProjected", "phase5PercentageSecondProjected"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IpcHistoricalDatumDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if analysis_title (nullable) is None
        # and model_fields_set contains the field
        if self.analysis_title is None and "analysis_title" in self.model_fields_set:
            _dict['analysisTitle'] = None

        # set to None if iso3_alpha3 (nullable) is None
        # and model_fields_set contains the field
        if self.iso3_alpha3 is None and "iso3_alpha3" in self.model_fields_set:
            _dict['iso3Alpha3'] = None

        # set to None if country_name (nullable) is None
        # and model_fields_set contains the field
        if self.country_name is None and "country_name" in self.model_fields_set:
            _dict['countryName'] = None

        # set to None if analysis_date (nullable) is None
        # and model_fields_set contains the field
        if self.analysis_date is None and "analysis_date" in self.model_fields_set:
            _dict['analysisDate'] = None

        # set to None if start_date_current_period (nullable) is None
        # and model_fields_set contains the field
        if self.start_date_current_period is None and "start_date_current_period" in self.model_fields_set:
            _dict['StartDate_CurrentPeriod'] = None

        # set to None if end_date_current_period (nullable) is None
        # and model_fields_set contains the field
        if self.end_date_current_period is None and "end_date_current_period" in self.model_fields_set:
            _dict['EndDate_CurrentPeriod'] = None

        # set to None if start_date_projected_period (nullable) is None
        # and model_fields_set contains the field
        if self.start_date_projected_period is None and "start_date_projected_period" in self.model_fields_set:
            _dict['StartDate_ProjectedPeriod'] = None

        # set to None if end_date_projected_period (nullable) is None
        # and model_fields_set contains the field
        if self.end_date_projected_period is None and "end_date_projected_period" in self.model_fields_set:
            _dict['EndDate_ProjectedPeriod'] = None

        # set to None if start_date_second_projected_period (nullable) is None
        # and model_fields_set contains the field
        if self.start_date_second_projected_period is None and "start_date_second_projected_period" in self.model_fields_set:
            _dict['StartDate_SecondProjectedPeriod'] = None

        # set to None if end_date_second_projected_period (nullable) is None
        # and model_fields_set contains the field
        if self.end_date_second_projected_period is None and "end_date_second_projected_period" in self.model_fields_set:
            _dict['EndDate_SecondProjectedPeriod'] = None

        # set to None if population (nullable) is None
        # and model_fields_set contains the field
        if self.population is None and "population" in self.model_fields_set:
            _dict['population'] = None

        # set to None if population_percentage (nullable) is None
        # and model_fields_set contains the field
        if self.population_percentage is None and "population_percentage" in self.model_fields_set:
            _dict['populationPercentage'] = None

        # set to None if phase3_plus_population (nullable) is None
        # and model_fields_set contains the field
        if self.phase3_plus_population is None and "phase3_plus_population" in self.model_fields_set:
            _dict['phase3PlusPopulation'] = None

        # set to None if phase3_plus_percentage (nullable) is None
        # and model_fields_set contains the field
        if self.phase3_plus_percentage is None and "phase3_plus_percentage" in self.model_fields_set:
            _dict['phase3PlusPercentage'] = None

        # set to None if estimated_population (nullable) is None
        # and model_fields_set contains the field
        if self.estimated_population is None and "estimated_population" in self.model_fields_set:
            _dict['estimatedPopulation'] = None

        # set to None if phase1_population (nullable) is None
        # and model_fields_set contains the field
        if self.phase1_population is None and "phase1_population" in self.model_fields_set:
            _dict['phase1Population'] = None

        # set to None if phase1_percentage (nullable) is None
        # and model_fields_set contains the field
        if self.phase1_percentage is None and "phase1_percentage" in self.model_fields_set:
            _dict['phase1Percentage'] = None

        # set to None if phase2_population (nullable) is None
        # and model_fields_set contains the field
        if self.phase2_population is None and "phase2_population" in self.model_fields_set:
            _dict['phase2Population'] = None

        # set to None if phase2_percentage (nullable) is None
        # and model_fields_set contains the field
        if self.phase2_percentage is None and "phase2_percentage" in self.model_fields_set:
            _dict['phase2Percentage'] = None

        # set to None if phase3_population (nullable) is None
        # and model_fields_set contains the field
        if self.phase3_population is None and "phase3_population" in self.model_fields_set:
            _dict['phase3Population'] = None

        # set to None if phase3_percentage (nullable) is None
        # and model_fields_set contains the field
        if self.phase3_percentage is None and "phase3_percentage" in self.model_fields_set:
            _dict['phase3Percentage'] = None

        # set to None if phase4_population (nullable) is None
        # and model_fields_set contains the field
        if self.phase4_population is None and "phase4_population" in self.model_fields_set:
            _dict['phase4Population'] = None

        # set to None if phase4_percentage (nullable) is None
        # and model_fields_set contains the field
        if self.phase4_percentage is None and "phase4_percentage" in self.model_fields_set:
            _dict['phase4Percentage'] = None

        # set to None if phase5_population (nullable) is None
        # and model_fields_set contains the field
        if self.phase5_population is None and "phase5_population" in self.model_fields_set:
            _dict['phase5Population'] = None

        # set to None if phase5_percentage (nullable) is None
        # and model_fields_set contains the field
        if self.phase5_percentage is None and "phase5_percentage" in self.model_fields_set:
            _dict['phase5Percentage'] = None

        # set to None if phase3_plus_population_projected (nullable) is None
        # and model_fields_set contains the field
        if self.phase3_plus_population_projected is None and "phase3_plus_population_projected" in self.model_fields_set:
            _dict['phase3PlusPopulationProjected'] = None

        # set to None if phase3_plus_percentage_projected (nullable) is None
        # and model_fields_set contains the field
        if self.phase3_plus_percentage_projected is None and "phase3_plus_percentage_projected" in self.model_fields_set:
            _dict['phase3PlusPercentageProjected'] = None

        # set to None if estimated_population_projected (nullable) is None
        # and model_fields_set contains the field
        if self.estimated_population_projected is None and "estimated_population_projected" in self.model_fields_set:
            _dict['estimatedPopulationProjected'] = None

        # set to None if phase1_population_projected (nullable) is None
        # and model_fields_set contains the field
        if self.phase1_population_projected is None and "phase1_population_projected" in self.model_fields_set:
            _dict['phase1PopulationProjected'] = None

        # set to None if phase1_percentage_projected (nullable) is None
        # and model_fields_set contains the field
        if self.phase1_percentage_projected is None and "phase1_percentage_projected" in self.model_fields_set:
            _dict['phase1PercentageProjected'] = None

        # set to None if phase2_population_projected (nullable) is None
        # and model_fields_set contains the field
        if self.phase2_population_projected is None and "phase2_population_projected" in self.model_fields_set:
            _dict['phase2PopulationProjected'] = None

        # set to None if phase2_percentage_projected (nullable) is None
        # and model_fields_set contains the field
        if self.phase2_percentage_projected is None and "phase2_percentage_projected" in self.model_fields_set:
            _dict['phase2PercentageProjected'] = None

        # set to None if phase3_population_projected (nullable) is None
        # and model_fields_set contains the field
        if self.phase3_population_projected is None and "phase3_population_projected" in self.model_fields_set:
            _dict['phase3PopulationProjected'] = None

        # set to None if phase3_percentage_projected (nullable) is None
        # and model_fields_set contains the field
        if self.phase3_percentage_projected is None and "phase3_percentage_projected" in self.model_fields_set:
            _dict['phase3PercentageProjected'] = None

        # set to None if phase4_population_projected (nullable) is None
        # and model_fields_set contains the field
        if self.phase4_population_projected is None and "phase4_population_projected" in self.model_fields_set:
            _dict['phase4PopulationProjected'] = None

        # set to None if phase4_percentage_projected (nullable) is None
        # and model_fields_set contains the field
        if self.phase4_percentage_projected is None and "phase4_percentage_projected" in self.model_fields_set:
            _dict['phase4PercentageProjected'] = None

        # set to None if phase5_population_projected (nullable) is None
        # and model_fields_set contains the field
        if self.phase5_population_projected is None and "phase5_population_projected" in self.model_fields_set:
            _dict['phase5PopulationProjected'] = None

        # set to None if phase5_percentage_projected (nullable) is None
        # and model_fields_set contains the field
        if self.phase5_percentage_projected is None and "phase5_percentage_projected" in self.model_fields_set:
            _dict['phase5PercentageProjected'] = None

        # set to None if phase3_plus_population_second_projected (nullable) is None
        # and model_fields_set contains the field
        if self.phase3_plus_population_second_projected is None and "phase3_plus_population_second_projected" in self.model_fields_set:
            _dict['phase3PlusPopulationSecondProjected'] = None

        # set to None if phase3_plus_percentage_second_projected (nullable) is None
        # and model_fields_set contains the field
        if self.phase3_plus_percentage_second_projected is None and "phase3_plus_percentage_second_projected" in self.model_fields_set:
            _dict['phase3PlusPercentageSecondProjected'] = None

        # set to None if estimated_population_second_projected (nullable) is None
        # and model_fields_set contains the field
        if self.estimated_population_second_projected is None and "estimated_population_second_projected" in self.model_fields_set:
            _dict['estimatedPopulationSecondProjected'] = None

        # set to None if phase1_population_second_projected (nullable) is None
        # and model_fields_set contains the field
        if self.phase1_population_second_projected is None and "phase1_population_second_projected" in self.model_fields_set:
            _dict['phase1PopulationSecondProjected'] = None

        # set to None if phase1_percentage_second_projected (nullable) is None
        # and model_fields_set contains the field
        if self.phase1_percentage_second_projected is None and "phase1_percentage_second_projected" in self.model_fields_set:
            _dict['phase1PercentageSecondProjected'] = None

        # set to None if phase2_population_second_projected (nullable) is None
        # and model_fields_set contains the field
        if self.phase2_population_second_projected is None and "phase2_population_second_projected" in self.model_fields_set:
            _dict['phase2PopulationSecondProjected'] = None

        # set to None if phase2_percentage_second_projected (nullable) is None
        # and model_fields_set contains the field
        if self.phase2_percentage_second_projected is None and "phase2_percentage_second_projected" in self.model_fields_set:
            _dict['phase2PercentageSecondProjected'] = None

        # set to None if phase3_population_second_projected (nullable) is None
        # and model_fields_set contains the field
        if self.phase3_population_second_projected is None and "phase3_population_second_projected" in self.model_fields_set:
            _dict['phase3PopulationSecondProjected'] = None

        # set to None if phase3_percentage_second_projected (nullable) is None
        # and model_fields_set contains the field
        if self.phase3_percentage_second_projected is None and "phase3_percentage_second_projected" in self.model_fields_set:
            _dict['phase3PercentageSecondProjected'] = None

        # set to None if phase4_population_second_projected (nullable) is None
        # and model_fields_set contains the field
        if self.phase4_population_second_projected is None and "phase4_population_second_projected" in self.model_fields_set:
            _dict['phase4PopulationSecondProjected'] = None

        # set to None if phase4_percentage_second_projected (nullable) is None
        # and model_fields_set contains the field
        if self.phase4_percentage_second_projected is None and "phase4_percentage_second_projected" in self.model_fields_set:
            _dict['phase4PercentageSecondProjected'] = None

        # set to None if phase5_population_second_projected (nullable) is None
        # and model_fields_set contains the field
        if self.phase5_population_second_projected is None and "phase5_population_second_projected" in self.model_fields_set:
            _dict['phase5PopulationSecondProjected'] = None

        # set to None if phase5_percentage_second_projected (nullable) is None
        # and model_fields_set contains the field
        if self.phase5_percentage_second_projected is None and "phase5_percentage_second_projected" in self.model_fields_set:
            _dict['phase5PercentageSecondProjected'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IpcHistoricalDatumDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "analysisId": obj.get("analysisId"),
            "analysisTitle": obj.get("analysisTitle"),
            "iso3Alpha3": obj.get("iso3Alpha3"),
            "countryName": obj.get("countryName"),
            "analysisDate": obj.get("analysisDate"),
            "StartDate_CurrentPeriod": obj.get("StartDate_CurrentPeriod"),
            "EndDate_CurrentPeriod": obj.get("EndDate_CurrentPeriod"),
            "StartDate_ProjectedPeriod": obj.get("StartDate_ProjectedPeriod"),
            "EndDate_ProjectedPeriod": obj.get("EndDate_ProjectedPeriod"),
            "StartDate_SecondProjectedPeriod": obj.get("StartDate_SecondProjectedPeriod"),
            "EndDate_SecondProjectedPeriod": obj.get("EndDate_SecondProjectedPeriod"),
            "population": obj.get("population"),
            "populationPercentage": obj.get("populationPercentage"),
            "phase3PlusPopulation": obj.get("phase3PlusPopulation"),
            "phase3PlusPercentage": obj.get("phase3PlusPercentage"),
            "estimatedPopulation": obj.get("estimatedPopulation"),
            "phase1Population": obj.get("phase1Population"),
            "phase1Percentage": obj.get("phase1Percentage"),
            "phase2Population": obj.get("phase2Population"),
            "phase2Percentage": obj.get("phase2Percentage"),
            "phase3Population": obj.get("phase3Population"),
            "phase3Percentage": obj.get("phase3Percentage"),
            "phase4Population": obj.get("phase4Population"),
            "phase4Percentage": obj.get("phase4Percentage"),
            "phase5Population": obj.get("phase5Population"),
            "phase5Percentage": obj.get("phase5Percentage"),
            "phase3PlusPopulationProjected": obj.get("phase3PlusPopulationProjected"),
            "phase3PlusPercentageProjected": obj.get("phase3PlusPercentageProjected"),
            "estimatedPopulationProjected": obj.get("estimatedPopulationProjected"),
            "phase1PopulationProjected": obj.get("phase1PopulationProjected"),
            "phase1PercentageProjected": obj.get("phase1PercentageProjected"),
            "phase2PopulationProjected": obj.get("phase2PopulationProjected"),
            "phase2PercentageProjected": obj.get("phase2PercentageProjected"),
            "phase3PopulationProjected": obj.get("phase3PopulationProjected"),
            "phase3PercentageProjected": obj.get("phase3PercentageProjected"),
            "phase4PopulationProjected": obj.get("phase4PopulationProjected"),
            "phase4PercentageProjected": obj.get("phase4PercentageProjected"),
            "phase5PopulationProjected": obj.get("phase5PopulationProjected"),
            "phase5PercentageProjected": obj.get("phase5PercentageProjected"),
            "phase3PlusPopulationSecondProjected": obj.get("phase3PlusPopulationSecondProjected"),
            "phase3PlusPercentageSecondProjected": obj.get("phase3PlusPercentageSecondProjected"),
            "estimatedPopulationSecondProjected": obj.get("estimatedPopulationSecondProjected"),
            "phase1PopulationSecondProjected": obj.get("phase1PopulationSecondProjected"),
            "phase1PercentageSecondProjected": obj.get("phase1PercentageSecondProjected"),
            "phase2PopulationSecondProjected": obj.get("phase2PopulationSecondProjected"),
            "phase2PercentageSecondProjected": obj.get("phase2PercentageSecondProjected"),
            "phase3PopulationSecondProjected": obj.get("phase3PopulationSecondProjected"),
            "phase3PercentageSecondProjected": obj.get("phase3PercentageSecondProjected"),
            "phase4PopulationSecondProjected": obj.get("phase4PopulationSecondProjected"),
            "phase4PercentageSecondProjected": obj.get("phase4PercentageSecondProjected"),
            "phase5PopulationSecondProjected": obj.get("phase5PopulationSecondProjected"),
            "phase5PercentageSecondProjected": obj.get("phase5PercentageSecondProjected")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


