# coding: utf-8

"""
    VAM-Data-Bridges

    API Documentation of the **DataBridges** platform: https://databridges.vam.wfp.org/. For API discussions and details: #api-integration-vam-data-bridges on Slack, [Teams channel](https://teams.microsoft.com/l/team/19%3a4ca595f7681f4ffa8a86b7af58832e8d%40thread.skype/conversations?groupId=cbd1e508-c6e8-459d-96b7-6cac3039c42c&tenantId=462ad9ae-d7d9-4206-b874-71b1e079776f) **API Integration** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern

    The version of the OpenAPI document: 7.0.0
    Contact: wfp.economicanalysis@wfp.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class IpcchBaseDto(BaseModel):
    """
    IpcchBaseDto
    """ # noqa: E501
    iso3_alpha3: Optional[StrictStr] = Field(default=None, alias="iso3Alpha3")
    country_name: Optional[StrictStr] = Field(default=None, alias="countryName")
    population_group_id: Optional[StrictInt] = Field(default=None, alias="populationGroupId")
    population_group_name: Optional[StrictStr] = Field(default=None, alias="populationGroupName")
    analysis_title: Optional[StrictStr] = Field(default=None, alias="analysisTitle")
    analysis_date: Optional[datetime] = Field(default=None, alias="analysisDate")
    period_start: Optional[datetime] = Field(default=None, alias="periodStart")
    period_end: Optional[datetime] = Field(default=None, alias="periodEnd")
    period_type: Optional[StrictStr] = Field(default=None, alias="periodType")
    population: Optional[Union[StrictFloat, StrictInt]] = None
    population_analysed: Optional[StrictInt] = Field(default=None, alias="populationAnalysed")
    population_analysed_percentage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="populationAnalysedPercentage")
    phase3_population: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase3Population")
    phase4_population: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase4Population")
    phase5_population: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase5Population")
    phase3_plus_population: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase3PlusPopulation")
    phase4_plus_population: Optional[StrictInt] = Field(default=None, alias="phase4PlusPopulation")
    phase3_percentage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase3Percentage")
    phase4_percentage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase4Percentage")
    phase5_percentage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase5Percentage")
    phase3_plus_percentage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase3PlusPercentage")
    phase4_plus_percentage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phase4PlusPercentage")
    data_source: Optional[StrictStr] = Field(default=None, alias="dataSource")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["iso3Alpha3", "countryName", "populationGroupId", "populationGroupName", "analysisTitle", "analysisDate", "periodStart", "periodEnd", "periodType", "population", "populationAnalysed", "populationAnalysedPercentage", "phase3Population", "phase4Population", "phase5Population", "phase3PlusPopulation", "phase4PlusPopulation", "phase3Percentage", "phase4Percentage", "phase5Percentage", "phase3PlusPercentage", "phase4PlusPercentage", "dataSource"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IpcchBaseDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if iso3_alpha3 (nullable) is None
        # and model_fields_set contains the field
        if self.iso3_alpha3 is None and "iso3_alpha3" in self.model_fields_set:
            _dict['iso3Alpha3'] = None

        # set to None if country_name (nullable) is None
        # and model_fields_set contains the field
        if self.country_name is None and "country_name" in self.model_fields_set:
            _dict['countryName'] = None

        # set to None if population_group_name (nullable) is None
        # and model_fields_set contains the field
        if self.population_group_name is None and "population_group_name" in self.model_fields_set:
            _dict['populationGroupName'] = None

        # set to None if analysis_title (nullable) is None
        # and model_fields_set contains the field
        if self.analysis_title is None and "analysis_title" in self.model_fields_set:
            _dict['analysisTitle'] = None

        # set to None if analysis_date (nullable) is None
        # and model_fields_set contains the field
        if self.analysis_date is None and "analysis_date" in self.model_fields_set:
            _dict['analysisDate'] = None

        # set to None if period_start (nullable) is None
        # and model_fields_set contains the field
        if self.period_start is None and "period_start" in self.model_fields_set:
            _dict['periodStart'] = None

        # set to None if period_end (nullable) is None
        # and model_fields_set contains the field
        if self.period_end is None and "period_end" in self.model_fields_set:
            _dict['periodEnd'] = None

        # set to None if period_type (nullable) is None
        # and model_fields_set contains the field
        if self.period_type is None and "period_type" in self.model_fields_set:
            _dict['periodType'] = None

        # set to None if population (nullable) is None
        # and model_fields_set contains the field
        if self.population is None and "population" in self.model_fields_set:
            _dict['population'] = None

        # set to None if population_analysed (nullable) is None
        # and model_fields_set contains the field
        if self.population_analysed is None and "population_analysed" in self.model_fields_set:
            _dict['populationAnalysed'] = None

        # set to None if population_analysed_percentage (nullable) is None
        # and model_fields_set contains the field
        if self.population_analysed_percentage is None and "population_analysed_percentage" in self.model_fields_set:
            _dict['populationAnalysedPercentage'] = None

        # set to None if phase3_population (nullable) is None
        # and model_fields_set contains the field
        if self.phase3_population is None and "phase3_population" in self.model_fields_set:
            _dict['phase3Population'] = None

        # set to None if phase4_population (nullable) is None
        # and model_fields_set contains the field
        if self.phase4_population is None and "phase4_population" in self.model_fields_set:
            _dict['phase4Population'] = None

        # set to None if phase5_population (nullable) is None
        # and model_fields_set contains the field
        if self.phase5_population is None and "phase5_population" in self.model_fields_set:
            _dict['phase5Population'] = None

        # set to None if phase3_plus_population (nullable) is None
        # and model_fields_set contains the field
        if self.phase3_plus_population is None and "phase3_plus_population" in self.model_fields_set:
            _dict['phase3PlusPopulation'] = None

        # set to None if phase4_plus_population (nullable) is None
        # and model_fields_set contains the field
        if self.phase4_plus_population is None and "phase4_plus_population" in self.model_fields_set:
            _dict['phase4PlusPopulation'] = None

        # set to None if phase3_percentage (nullable) is None
        # and model_fields_set contains the field
        if self.phase3_percentage is None and "phase3_percentage" in self.model_fields_set:
            _dict['phase3Percentage'] = None

        # set to None if phase4_percentage (nullable) is None
        # and model_fields_set contains the field
        if self.phase4_percentage is None and "phase4_percentage" in self.model_fields_set:
            _dict['phase4Percentage'] = None

        # set to None if phase5_percentage (nullable) is None
        # and model_fields_set contains the field
        if self.phase5_percentage is None and "phase5_percentage" in self.model_fields_set:
            _dict['phase5Percentage'] = None

        # set to None if phase3_plus_percentage (nullable) is None
        # and model_fields_set contains the field
        if self.phase3_plus_percentage is None and "phase3_plus_percentage" in self.model_fields_set:
            _dict['phase3PlusPercentage'] = None

        # set to None if phase4_plus_percentage (nullable) is None
        # and model_fields_set contains the field
        if self.phase4_plus_percentage is None and "phase4_plus_percentage" in self.model_fields_set:
            _dict['phase4PlusPercentage'] = None

        # set to None if data_source (nullable) is None
        # and model_fields_set contains the field
        if self.data_source is None and "data_source" in self.model_fields_set:
            _dict['dataSource'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IpcchBaseDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "iso3Alpha3": obj.get("iso3Alpha3"),
            "countryName": obj.get("countryName"),
            "populationGroupId": obj.get("populationGroupId"),
            "populationGroupName": obj.get("populationGroupName"),
            "analysisTitle": obj.get("analysisTitle"),
            "analysisDate": obj.get("analysisDate"),
            "periodStart": obj.get("periodStart"),
            "periodEnd": obj.get("periodEnd"),
            "periodType": obj.get("periodType"),
            "population": obj.get("population"),
            "populationAnalysed": obj.get("populationAnalysed"),
            "populationAnalysedPercentage": obj.get("populationAnalysedPercentage"),
            "phase3Population": obj.get("phase3Population"),
            "phase4Population": obj.get("phase4Population"),
            "phase5Population": obj.get("phase5Population"),
            "phase3PlusPopulation": obj.get("phase3PlusPopulation"),
            "phase4PlusPopulation": obj.get("phase4PlusPopulation"),
            "phase3Percentage": obj.get("phase3Percentage"),
            "phase4Percentage": obj.get("phase4Percentage"),
            "phase5Percentage": obj.get("phase5Percentage"),
            "phase3PlusPercentage": obj.get("phase3PlusPercentage"),
            "phase4PlusPercentage": obj.get("phase4PlusPercentage"),
            "dataSource": obj.get("dataSource")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


