# coding: utf-8

# flake8: noqa

"""
VAMDataBridges

API Documentation of the **DataBridges** platform: https://databridges.vam.wfp.org/. For API discussions and details: #api-integration-vam-data-bridges on Slack, [Teams channel](https://teams.microsoft.com/l/team/19%3a4ca595f7681f4ffa8a86b7af58832e8d%40thread.skype/conversations?groupId=cbd1e508-c6e8-459d-96b7-6cac3039c42c&tenantId=462ad9ae-d7d9-4206-b874-71b1e079776f) **API Integration** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern

The version of the OpenAPI document: v2
Contact: wfp.economicanalysis@wfp.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

__version__ = "9.0.0"

# Define package exports
__all__ = [
    "CommoditiesApi",
    "CommodityUnitsApi",
    "CurrencyApi",
    "EconomicDataApi",
    "GlobalOutlookApi",
    "HungerHotspotApi",
    "IncubationApi",
    "IpcchApi",
    "MarketPricesApi",
    "MarketsApi",
    "RpmeApi",
    "SurveysApi",
    "XlsFormsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "BadRequestDTO",
    "CariAdm0ValuesDTO",
    "CariAdm0ValuesDTOPagedResult",
    "CariAdm1ValuesDTO",
    "CariAdm1ValuesDTOPagedResult",
    "CategoriesAndIndicatorsDTO",
    "CommodityDTO",
    "CommodityPriceDTO",
    "CommodityProcessingDTO",
    "CommodityQualityDTO",
    "CurrencyDTO",
    "EconomicDataDTO",
    "EconomicIndicatorProperty",
    "EconomicIndicatorPropertyPagedResult",
    "ExtendedAlpsValueDto",
    "ExtendedAlpsValueDtoPagedResult",
    "Feature",
    "Geometry",
    "GlobalOutlookApiDto",
    "GlobalOutlookCountryApiDto",
    "GlobalOutlookRegionalApiDto",
    "HouseholdSurveyListDTO",
    "HouseholdSurveyListDTOPagedResult",
    "HungerHotSpotDataDTO",
    "HungerHotSpotDataDTOPagedResult",
    "IpcHistoricalDatumDto",
    "IpcHistoricalDatumDtoPagedResult",
    "IpcchAndEquivalentPeaksDTO",
    "IpcchAndEquivalentPeaksDTOPagedResult",
    "IpcchBaseDto",
    "IpcchBaseDtoPagedResult",
    "IpcchPeaksDto",
    "IpcchPeaksDtoPagedResult",
    "KeyNameDto",
    "ListItemDto",
    "MFIProcessedDataDTO",
    "MarketDTO",
    "MarketGeoJsonRoot",
    "NearbyMarketsDTO",
    "PagedCommodityListDTO",
    "PagedCommodityPriceListDTO",
    "PagedCommodityWeeklyAggregatedPriceListDTO",
    "PagedCurrencyListDTO",
    "PagedEconomicDataDTO",
    "PagedMarketListDTO",
    "PagedProcessedDataDTO",
    "PagedSurveyListDTO",
    "PagedSurveyResponsesDTO",
    "PagedXlsFormListDTO",
    "ProblemDetails",
    "Properties",
    "RpmeAssessment",
    "RpmeAssessmentPagedResult",
    "RpmeOutputValues",
    "RpmeVariable",
    "RpmeVariablePagedResult",
    "SurveyListDTO",
    "UsdIndirectQuotation",
    "UsdIndirectQuotationPagedResult",
    "ViewExtendedMonthlyAggregatedPrice",
    "ViewExtendedMonthlyAggregatedPricePagedResult",
    "WeeklyAggregatedPrice",
    "XlsFormDTO",
    "XlsFormDefinitionNewSchemaDTO",
    "XlsFormFieldsDTO",
    "XlsFormListChoiceDTO",
    "XlsFormListChoicesDTO",
]

# import apis into sdk package
from data_bridges_client.api.commodities_api import CommoditiesApi as CommoditiesApi
from data_bridges_client.api.commodity_units_api import (
    CommodityUnitsApi as CommodityUnitsApi,
)
from data_bridges_client.api.currency_api import CurrencyApi as CurrencyApi
from data_bridges_client.api.economic_data_api import EconomicDataApi as EconomicDataApi
from data_bridges_client.api.global_outlook_api import (
    GlobalOutlookApi as GlobalOutlookApi,
)
from data_bridges_client.api.hunger_hotspot_api import (
    HungerHotspotApi as HungerHotspotApi,
)
from data_bridges_client.api.incubation_api import IncubationApi as IncubationApi
from data_bridges_client.api.ipcch_api import IpcchApi as IpcchApi
from data_bridges_client.api.market_prices_api import MarketPricesApi as MarketPricesApi
from data_bridges_client.api.markets_api import MarketsApi as MarketsApi
from data_bridges_client.api.rpme_api import RpmeApi as RpmeApi
from data_bridges_client.api.surveys_api import SurveysApi as SurveysApi
from data_bridges_client.api.xls_forms_api import XlsFormsApi as XlsFormsApi
from data_bridges_client.api_client import ApiClient as ApiClient

# import ApiClient
from data_bridges_client.api_response import ApiResponse as ApiResponse
from data_bridges_client.configuration import Configuration as Configuration
from data_bridges_client.exceptions import ApiAttributeError as ApiAttributeError
from data_bridges_client.exceptions import ApiException as ApiException
from data_bridges_client.exceptions import ApiKeyError as ApiKeyError
from data_bridges_client.exceptions import ApiTypeError as ApiTypeError
from data_bridges_client.exceptions import ApiValueError as ApiValueError
from data_bridges_client.exceptions import OpenApiException as OpenApiException

# import models into sdk package
from data_bridges_client.models.bad_request_dto import BadRequestDTO as BadRequestDTO
from data_bridges_client.models.cari_adm0_values_dto import (
    CariAdm0ValuesDTO as CariAdm0ValuesDTO,
)
from data_bridges_client.models.cari_adm0_values_dto_paged_result import (
    CariAdm0ValuesDTOPagedResult as CariAdm0ValuesDTOPagedResult,
)
from data_bridges_client.models.cari_adm1_values_dto import (
    CariAdm1ValuesDTO as CariAdm1ValuesDTO,
)
from data_bridges_client.models.cari_adm1_values_dto_paged_result import (
    CariAdm1ValuesDTOPagedResult as CariAdm1ValuesDTOPagedResult,
)
from data_bridges_client.models.categories_and_indicators_dto import (
    CategoriesAndIndicatorsDTO as CategoriesAndIndicatorsDTO,
)
from data_bridges_client.models.commodity_dto import CommodityDTO as CommodityDTO
from data_bridges_client.models.commodity_price_dto import (
    CommodityPriceDTO as CommodityPriceDTO,
)
from data_bridges_client.models.commodity_processing_dto import (
    CommodityProcessingDTO as CommodityProcessingDTO,
)
from data_bridges_client.models.commodity_quality_dto import (
    CommodityQualityDTO as CommodityQualityDTO,
)
from data_bridges_client.models.currency_dto import CurrencyDTO as CurrencyDTO
from data_bridges_client.models.economic_data_dto import (
    EconomicDataDTO as EconomicDataDTO,
)
from data_bridges_client.models.economic_indicator_property import (
    EconomicIndicatorProperty as EconomicIndicatorProperty,
)
from data_bridges_client.models.economic_indicator_property_paged_result import (
    EconomicIndicatorPropertyPagedResult as EconomicIndicatorPropertyPagedResult,
)
from data_bridges_client.models.extended_alps_value_dto import (
    ExtendedAlpsValueDto as ExtendedAlpsValueDto,
)
from data_bridges_client.models.extended_alps_value_dto_paged_result import (
    ExtendedAlpsValueDtoPagedResult as ExtendedAlpsValueDtoPagedResult,
)
from data_bridges_client.models.feature import Feature as Feature
from data_bridges_client.models.geometry import Geometry as Geometry
from data_bridges_client.models.global_outlook_api_dto import (
    GlobalOutlookApiDto as GlobalOutlookApiDto,
)
from data_bridges_client.models.global_outlook_country_api_dto import (
    GlobalOutlookCountryApiDto as GlobalOutlookCountryApiDto,
)
from data_bridges_client.models.global_outlook_regional_api_dto import (
    GlobalOutlookRegionalApiDto as GlobalOutlookRegionalApiDto,
)
from data_bridges_client.models.household_survey_list_dto import (
    HouseholdSurveyListDTO as HouseholdSurveyListDTO,
)
from data_bridges_client.models.household_survey_list_dto_paged_result import (
    HouseholdSurveyListDTOPagedResult as HouseholdSurveyListDTOPagedResult,
)
from data_bridges_client.models.hunger_hot_spot_data_dto import (
    HungerHotSpotDataDTO as HungerHotSpotDataDTO,
)
from data_bridges_client.models.hunger_hot_spot_data_dto_paged_result import (
    HungerHotSpotDataDTOPagedResult as HungerHotSpotDataDTOPagedResult,
)
from data_bridges_client.models.ipc_historical_datum_dto import (
    IpcHistoricalDatumDto as IpcHistoricalDatumDto,
)
from data_bridges_client.models.ipc_historical_datum_dto_paged_result import (
    IpcHistoricalDatumDtoPagedResult as IpcHistoricalDatumDtoPagedResult,
)
from data_bridges_client.models.ipcch_and_equivalent_peaks_dto import (
    IpcchAndEquivalentPeaksDTO as IpcchAndEquivalentPeaksDTO,
)
from data_bridges_client.models.ipcch_and_equivalent_peaks_dto_paged_result import (
    IpcchAndEquivalentPeaksDTOPagedResult as IpcchAndEquivalentPeaksDTOPagedResult,
)
from data_bridges_client.models.ipcch_base_dto import IpcchBaseDto as IpcchBaseDto
from data_bridges_client.models.ipcch_base_dto_paged_result import (
    IpcchBaseDtoPagedResult as IpcchBaseDtoPagedResult,
)
from data_bridges_client.models.ipcch_peaks_dto import IpcchPeaksDto as IpcchPeaksDto
from data_bridges_client.models.ipcch_peaks_dto_paged_result import (
    IpcchPeaksDtoPagedResult as IpcchPeaksDtoPagedResult,
)
from data_bridges_client.models.key_name_dto import KeyNameDto as KeyNameDto
from data_bridges_client.models.list_item_dto import ListItemDto as ListItemDto
from data_bridges_client.models.market_dto import MarketDTO as MarketDTO
from data_bridges_client.models.market_geo_json_root import (
    MarketGeoJsonRoot as MarketGeoJsonRoot,
)
from data_bridges_client.models.mfi_processed_data_dto import (
    MFIProcessedDataDTO as MFIProcessedDataDTO,
)
from data_bridges_client.models.nearby_markets_dto import (
    NearbyMarketsDTO as NearbyMarketsDTO,
)
from data_bridges_client.models.paged_commodity_list_dto import (
    PagedCommodityListDTO as PagedCommodityListDTO,
)
from data_bridges_client.models.paged_commodity_price_list_dto import (
    PagedCommodityPriceListDTO as PagedCommodityPriceListDTO,
)
from data_bridges_client.models.paged_commodity_weekly_aggregated_price_list_dto import (
    PagedCommodityWeeklyAggregatedPriceListDTO as PagedCommodityWeeklyAggregatedPriceListDTO,
)
from data_bridges_client.models.paged_currency_list_dto import (
    PagedCurrencyListDTO as PagedCurrencyListDTO,
)
from data_bridges_client.models.paged_economic_data_dto import (
    PagedEconomicDataDTO as PagedEconomicDataDTO,
)
from data_bridges_client.models.paged_market_list_dto import (
    PagedMarketListDTO as PagedMarketListDTO,
)
from data_bridges_client.models.paged_processed_data_dto import (
    PagedProcessedDataDTO as PagedProcessedDataDTO,
)
from data_bridges_client.models.paged_survey_list_dto import (
    PagedSurveyListDTO as PagedSurveyListDTO,
)
from data_bridges_client.models.paged_survey_responses_dto import (
    PagedSurveyResponsesDTO as PagedSurveyResponsesDTO,
)
from data_bridges_client.models.paged_xls_form_list_dto import (
    PagedXlsFormListDTO as PagedXlsFormListDTO,
)
from data_bridges_client.models.problem_details import ProblemDetails as ProblemDetails
from data_bridges_client.models.properties import Properties as Properties
from data_bridges_client.models.rpme_assessment import RpmeAssessment as RpmeAssessment
from data_bridges_client.models.rpme_assessment_paged_result import (
    RpmeAssessmentPagedResult as RpmeAssessmentPagedResult,
)
from data_bridges_client.models.rpme_output_values import (
    RpmeOutputValues as RpmeOutputValues,
)
from data_bridges_client.models.rpme_variable import RpmeVariable as RpmeVariable
from data_bridges_client.models.rpme_variable_paged_result import (
    RpmeVariablePagedResult as RpmeVariablePagedResult,
)
from data_bridges_client.models.survey_list_dto import SurveyListDTO as SurveyListDTO
from data_bridges_client.models.usd_indirect_quotation import (
    UsdIndirectQuotation as UsdIndirectQuotation,
)
from data_bridges_client.models.usd_indirect_quotation_paged_result import (
    UsdIndirectQuotationPagedResult as UsdIndirectQuotationPagedResult,
)
from data_bridges_client.models.view_extended_monthly_aggregated_price import (
    ViewExtendedMonthlyAggregatedPrice as ViewExtendedMonthlyAggregatedPrice,
)
from data_bridges_client.models.view_extended_monthly_aggregated_price_paged_result import (
    ViewExtendedMonthlyAggregatedPricePagedResult as ViewExtendedMonthlyAggregatedPricePagedResult,
)
from data_bridges_client.models.weekly_aggregated_price import (
    WeeklyAggregatedPrice as WeeklyAggregatedPrice,
)
from data_bridges_client.models.xls_form_definition_new_schema_dto import (
    XlsFormDefinitionNewSchemaDTO as XlsFormDefinitionNewSchemaDTO,
)
from data_bridges_client.models.xls_form_dto import XlsFormDTO as XlsFormDTO
from data_bridges_client.models.xls_form_fields_dto import (
    XlsFormFieldsDTO as XlsFormFieldsDTO,
)
from data_bridges_client.models.xls_form_list_choice_dto import (
    XlsFormListChoiceDTO as XlsFormListChoiceDTO,
)
from data_bridges_client.models.xls_form_list_choices_dto import (
    XlsFormListChoicesDTO as XlsFormListChoicesDTO,
)
