# coding: utf-8

"""
VAMDataBridges

API Documentation of the **DataBridges** platform: https://databridges.vam.wfp.org/. For API discussions and details: #api-integration-vam-data-bridges on Slack, [Teams channel](https://teams.microsoft.com/l/team/19%3a4ca595f7681f4ffa8a86b7af58832e8d%40thread.skype/conversations?groupId=cbd1e508-c6e8-459d-96b7-6cac3039c42c&tenantId=462ad9ae-d7d9-4206-b874-71b1e079776f) **API Integration** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern

The version of the OpenAPI document: v1
Contact: wfp.economicanalysis@wfp.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from data_bridges_client.models.ipc_historical_datum_dto import IpcHistoricalDatumDto


class TestIpcHistoricalDatumDto(unittest.TestCase):
    """IpcHistoricalDatumDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IpcHistoricalDatumDto:
        """Test IpcHistoricalDatumDto
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `IpcHistoricalDatumDto`
        """
        model = IpcHistoricalDatumDto()
        if include_optional:
            return IpcHistoricalDatumDto(
                analysis_id = 56,
                analysis_title = '',
                iso3_alpha3 = '',
                country_name = '',
                analysis_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                start_date_current_period = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_date_current_period = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                start_date_projected_period = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_date_projected_period = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                start_date_second_projected_period = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_date_second_projected_period = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                population = 1.337,
                population_percentage = 1.337,
                phase3_plus_population = 1.337,
                phase3_plus_percentage = 1.337,
                estimated_population = 1.337,
                phase1_population = 1.337,
                phase1_percentage = 1.337,
                phase2_population = 1.337,
                phase2_percentage = 1.337,
                phase3_population = 1.337,
                phase3_percentage = 1.337,
                phase4_population = 1.337,
                phase4_percentage = 1.337,
                phase5_population = 1.337,
                phase5_percentage = 1.337,
                phase3_plus_population_projected = 1.337,
                phase3_plus_percentage_projected = 1.337,
                estimated_population_projected = 1.337,
                phase1_population_projected = 1.337,
                phase1_percentage_projected = 1.337,
                phase2_population_projected = 1.337,
                phase2_percentage_projected = 1.337,
                phase3_population_projected = 1.337,
                phase3_percentage_projected = 1.337,
                phase4_population_projected = 1.337,
                phase4_percentage_projected = 1.337,
                phase5_population_projected = 1.337,
                phase5_percentage_projected = 1.337,
                phase3_plus_population_second_projected = 1.337,
                phase3_plus_percentage_second_projected = 1.337,
                estimated_population_second_projected = 1.337,
                phase1_population_second_projected = 1.337,
                phase1_percentage_second_projected = 1.337,
                phase2_population_second_projected = 1.337,
                phase2_percentage_second_projected = 1.337,
                phase3_population_second_projected = 1.337,
                phase3_percentage_second_projected = 1.337,
                phase4_population_second_projected = 1.337,
                phase4_percentage_second_projected = 1.337,
                phase5_population_second_projected = 1.337,
                phase5_percentage_second_projected = 1.337
            )
        else:
            return IpcHistoricalDatumDto(
        )
        """

    def testIpcHistoricalDatumDto(self):
        """Test IpcHistoricalDatumDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
