# coding: utf-8

"""
VAMDataBridges

API Documentation of the **DataBridges** platform: https://databridges.vam.wfp.org/. For API discussions and details: #api-integration-vam-data-bridges on Slack, [Teams channel](https://teams.microsoft.com/l/team/19%3a4ca595f7681f4ffa8a86b7af58832e8d%40thread.skype/conversations?groupId=cbd1e508-c6e8-459d-96b7-6cac3039c42c&tenantId=462ad9ae-d7d9-4206-b874-71b1e079776f) **API Integration** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern

The version of the OpenAPI document: v2
Contact: wfp.economicanalysis@wfp.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from data_bridges_client.api.ipcch_api import IpcchApi


class TestIpcchApi(unittest.TestCase):
    """IpcchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IpcchApi()

    def tearDown(self) -> None:
        pass

    def test_ipcch_ipcch_and_equivalent_historical_peaks_get(self) -> None:
        """Test case for ipcch_ipcch_and_equivalent_historical_peaks_get

        Retrieves a paginated list of historical IPCCH and Equivalent peaks data, optionally filtered by ISO3 country code.
        """
        pass

    def test_ipcch_ipcch_and_equivalent_latest_peaks_get(self) -> None:
        """Test case for ipcch_ipcch_and_equivalent_latest_peaks_get

        Retrieves a paginated list of the latest IPCCH and Equivalent peaks data, optionally filtered by ISO3 country code.
        """
        pass

    def test_ipcch_ipcch_and_equivalent_most_recent_get(self) -> None:
        """Test case for ipcch_ipcch_and_equivalent_most_recent_get

        Retrieves a paginated list of the most recent IPCCH and Equivalent data, optionally filtered by ISO3 country code.
        """
        pass

    def test_ipcch_ipcch_and_equivalent_peaks_wfp_dashboard_get(self) -> None:
        """Test case for ipcch_ipcch_and_equivalent_peaks_wfp_dashboard_get

        Retrieves a paginated list of IPCCH and Equivalent Peaks data for the WFP Dashboard.
        """
        pass

    def test_ipcch_ipcch_historical_data_get(self) -> None:
        """Test case for ipcch_ipcch_historical_data_get

        Retrieves a paginated list of IPCCH and Equivalent Historical Data.
        """
        pass


if __name__ == "__main__":
    unittest.main()
