# coding: utf-8

"""
VAMDataBridges

API Documentation of the **DataBridges** platform: https://databridges.vam.wfp.org/. For API discussions and details: #api-integration-vam-data-bridges on Slack, [Teams channel](https://teams.microsoft.com/l/team/19%3a4ca595f7681f4ffa8a86b7af58832e8d%40thread.skype/conversations?groupId=cbd1e508-c6e8-459d-96b7-6cac3039c42c&tenantId=462ad9ae-d7d9-4206-b874-71b1e079776f) **API Integration** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern

The version of the OpenAPI document: v1
Contact: wfp.economicanalysis@wfp.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from data_bridges_client.models.cari_adm0_values_dto import CariAdm0ValuesDTO


class TestCariAdm0ValuesDTO(unittest.TestCase):
    """CariAdm0ValuesDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CariAdm0ValuesDTO:
        """Test CariAdm0ValuesDTO
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CariAdm0ValuesDTO`
        """
        model = CariAdm0ValuesDTO()
        if include_optional:
            return CariAdm0ValuesDTO(
                survey_id = 56,
                survey_name = '',
                cari_methodology_name = '',
                fcs_methodology_name = '',
                additional_survey_metadata = '',
                adm0_code = 56,
                adm0_name = '',
                cari_indicator_id = 56,
                cari_indicator_name = '',
                cari_indicator_category_id = 56,
                indicator_category_label = ''
            )
        else:
            return CariAdm0ValuesDTO(
        )
        """

    def testCariAdm0ValuesDTO(self):
        """Test CariAdm0ValuesDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
