"""
VAMDataBridges

API Documentation of the **DataBridges** platform: https://databridges.vam.wfp.org/. For API discussions and details: #api-integration-vam-data-bridges on Slack, [Teams channel](https://teams.microsoft.com/l/team/19%3a4ca595f7681f4ffa8a86b7af58832e8d%40thread.skype/conversations?groupId=cbd1e508-c6e8-459d-96b7-6cac3039c42c&tenantId=462ad9ae-d7d9-4206-b874-71b1e079776f) **API Integration** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern

The version of the OpenAPI document: v1
Contact: wfp.economicanalysis@wfp.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple, Union

from pydantic import Field, StrictFloat, StrictInt, StrictStr, validate_call
from typing_extensions import Annotated

from data_bridges_client.api_client import ApiClient, RequestSerialized
from data_bridges_client.api_response import ApiResponse
from data_bridges_client.models.ipc_historical_datum_dto_paged_result import (
    IpcHistoricalDatumDtoPagedResult,
)
from data_bridges_client.models.ipcch_and_equivalent_peaks_dto_paged_result import (
    IpcchAndEquivalentPeaksDTOPagedResult,
)
from data_bridges_client.models.ipcch_base_dto_paged_result import (
    IpcchBaseDtoPagedResult,
)
from data_bridges_client.models.ipcch_peaks_dto_paged_result import (
    IpcchPeaksDtoPagedResult,
)
from data_bridges_client.rest import RESTResponseType


class IpcchApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_call
    def ipcch_ipcch_and_equivalent_historical_peaks_get(
        self,
        reference_year: Annotated[
            Optional[StrictInt],
            Field(description="Year in a 4 digit format, for example: 2025"),
        ] = None,
        iso3: Optional[StrictStr] = None,
        page: Optional[StrictInt] = None,
        env: Annotated[
            Optional[StrictStr],
            Field(
                description="Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org"
            ),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> IpcchPeaksDtoPagedResult:
        """Retrieves a paginated list of historical IPCCH and Equivalent peaks data, optionally filtered by ISO3 country code.

          ![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)  ![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)  ![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)  ### This endpoint is restricted, it requires the permission: \"vamdatabridges\\_ipcch-ipcchandequivalent-historicalpeaks\\_get\"      **Data Controller** - Wael ATTIA  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern

        :param reference_year: Year in a 4 digit format, for example: 2025
        :type reference_year: int
        :param iso3:
        :type iso3: str
        :param page:
        :type page: int
        :param env: Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
        :type env: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._ipcch_ipcch_and_equivalent_historical_peaks_get_serialize(
            reference_year=reference_year,
            iso3=iso3,
            page=page,
            env=env,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "IpcchPeaksDtoPagedResult",
            "400": "BadRequestDTO",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def ipcch_ipcch_and_equivalent_historical_peaks_get_with_http_info(
        self,
        reference_year: Annotated[
            Optional[StrictInt],
            Field(description="Year in a 4 digit format, for example: 2025"),
        ] = None,
        iso3: Optional[StrictStr] = None,
        page: Optional[StrictInt] = None,
        env: Annotated[
            Optional[StrictStr],
            Field(
                description="Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org"
            ),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[IpcchPeaksDtoPagedResult]:
        """Retrieves a paginated list of historical IPCCH and Equivalent peaks data, optionally filtered by ISO3 country code.

          ![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)  ![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)  ![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)  ### This endpoint is restricted, it requires the permission: \"vamdatabridges\\_ipcch-ipcchandequivalent-historicalpeaks\\_get\"      **Data Controller** - Wael ATTIA  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern

        :param reference_year: Year in a 4 digit format, for example: 2025
        :type reference_year: int
        :param iso3:
        :type iso3: str
        :param page:
        :type page: int
        :param env: Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
        :type env: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._ipcch_ipcch_and_equivalent_historical_peaks_get_serialize(
            reference_year=reference_year,
            iso3=iso3,
            page=page,
            env=env,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "IpcchPeaksDtoPagedResult",
            "400": "BadRequestDTO",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def ipcch_ipcch_and_equivalent_historical_peaks_get_without_preload_content(
        self,
        reference_year: Annotated[
            Optional[StrictInt],
            Field(description="Year in a 4 digit format, for example: 2025"),
        ] = None,
        iso3: Optional[StrictStr] = None,
        page: Optional[StrictInt] = None,
        env: Annotated[
            Optional[StrictStr],
            Field(
                description="Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org"
            ),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Retrieves a paginated list of historical IPCCH and Equivalent peaks data, optionally filtered by ISO3 country code.

          ![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)  ![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)  ![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)  ### This endpoint is restricted, it requires the permission: \"vamdatabridges\\_ipcch-ipcchandequivalent-historicalpeaks\\_get\"      **Data Controller** - Wael ATTIA  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern

        :param reference_year: Year in a 4 digit format, for example: 2025
        :type reference_year: int
        :param iso3:
        :type iso3: str
        :param page:
        :type page: int
        :param env: Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
        :type env: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._ipcch_ipcch_and_equivalent_historical_peaks_get_serialize(
            reference_year=reference_year,
            iso3=iso3,
            page=page,
            env=env,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "IpcchPeaksDtoPagedResult",
            "400": "BadRequestDTO",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        return response_data.response

    def _ipcch_ipcch_and_equivalent_historical_peaks_get_serialize(
        self,
        reference_year,
        iso3,
        page,
        env,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {}

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if reference_year is not None:

            _query_params.append(("referenceYear", reference_year))

        if iso3 is not None:

            _query_params.append(("iso3", iso3))

        if page is not None:

            _query_params.append(("page", page))

        if env is not None:

            _query_params.append(("env", env))

        # process the header parameters
        # process the form parameters
        # process the body parameter

        # set the HTTP header `Accept`
        if "Accept" not in _header_params:
            _header_params["Accept"] = self.api_client.select_header_accept(
                ["text/plain", "application/json", "text/json"]
            )

        # authentication setting
        _auth_settings: List[str] = ["default"]

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/Ipcch/IPCCHAndEquivalent-HistoricalPeaks",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )

    @validate_call
    def ipcch_ipcch_and_equivalent_latest_peaks_get(
        self,
        iso3: Optional[StrictStr] = None,
        page: Optional[StrictInt] = None,
        env: Annotated[
            Optional[StrictStr],
            Field(
                description="Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org"
            ),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> IpcchPeaksDtoPagedResult:
        """Retrieves a paginated list of the latest IPCCH and Equivalent peaks data, optionally filtered by ISO3 country code.

          ![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)  ![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)  ![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)  ### This endpoint is restricted, it requires the permission: \"vamdatabridges\\_ipcch-ipcchandequivalent-latestpeaks\\_get\"      **Data Controller** - Wael ATTIA  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern

        :param iso3:
        :type iso3: str
        :param page:
        :type page: int
        :param env: Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
        :type env: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._ipcch_ipcch_and_equivalent_latest_peaks_get_serialize(
            iso3=iso3,
            page=page,
            env=env,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "IpcchPeaksDtoPagedResult",
            "400": "BadRequestDTO",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def ipcch_ipcch_and_equivalent_latest_peaks_get_with_http_info(
        self,
        iso3: Optional[StrictStr] = None,
        page: Optional[StrictInt] = None,
        env: Annotated[
            Optional[StrictStr],
            Field(
                description="Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org"
            ),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[IpcchPeaksDtoPagedResult]:
        """Retrieves a paginated list of the latest IPCCH and Equivalent peaks data, optionally filtered by ISO3 country code.

          ![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)  ![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)  ![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)  ### This endpoint is restricted, it requires the permission: \"vamdatabridges\\_ipcch-ipcchandequivalent-latestpeaks\\_get\"      **Data Controller** - Wael ATTIA  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern

        :param iso3:
        :type iso3: str
        :param page:
        :type page: int
        :param env: Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
        :type env: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._ipcch_ipcch_and_equivalent_latest_peaks_get_serialize(
            iso3=iso3,
            page=page,
            env=env,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "IpcchPeaksDtoPagedResult",
            "400": "BadRequestDTO",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def ipcch_ipcch_and_equivalent_latest_peaks_get_without_preload_content(
        self,
        iso3: Optional[StrictStr] = None,
        page: Optional[StrictInt] = None,
        env: Annotated[
            Optional[StrictStr],
            Field(
                description="Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org"
            ),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Retrieves a paginated list of the latest IPCCH and Equivalent peaks data, optionally filtered by ISO3 country code.

          ![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)  ![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)  ![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)  ### This endpoint is restricted, it requires the permission: \"vamdatabridges\\_ipcch-ipcchandequivalent-latestpeaks\\_get\"      **Data Controller** - Wael ATTIA  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern

        :param iso3:
        :type iso3: str
        :param page:
        :type page: int
        :param env: Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
        :type env: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._ipcch_ipcch_and_equivalent_latest_peaks_get_serialize(
            iso3=iso3,
            page=page,
            env=env,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "IpcchPeaksDtoPagedResult",
            "400": "BadRequestDTO",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        return response_data.response

    def _ipcch_ipcch_and_equivalent_latest_peaks_get_serialize(
        self,
        iso3,
        page,
        env,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {}

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if iso3 is not None:

            _query_params.append(("iso3", iso3))

        if page is not None:

            _query_params.append(("page", page))

        if env is not None:

            _query_params.append(("env", env))

        # process the header parameters
        # process the form parameters
        # process the body parameter

        # set the HTTP header `Accept`
        if "Accept" not in _header_params:
            _header_params["Accept"] = self.api_client.select_header_accept(
                ["text/plain", "application/json", "text/json"]
            )

        # authentication setting
        _auth_settings: List[str] = ["default"]

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/Ipcch/IPCCHAndEquivalent-LatestPeaks",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )

    @validate_call
    def ipcch_ipcch_and_equivalent_most_recent_get(
        self,
        iso3: Optional[StrictStr] = None,
        page: Optional[StrictInt] = None,
        env: Annotated[
            Optional[StrictStr],
            Field(
                description="Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org"
            ),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> IpcchBaseDtoPagedResult:
        """Retrieves a paginated list of the most recent IPCCH and Equivalent data, optionally filtered by ISO3 country code.

          ![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)  ![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)  ![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)  ### This endpoint is restricted, it requires the permission: \"vamdatabridges\\_ipcch-ipcchandequivalent-mostrecent\\_get\"      **Data Controller** - Wael ATTIA  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern

        :param iso3:
        :type iso3: str
        :param page:
        :type page: int
        :param env: Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
        :type env: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._ipcch_ipcch_and_equivalent_most_recent_get_serialize(
            iso3=iso3,
            page=page,
            env=env,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "IpcchBaseDtoPagedResult",
            "400": "BadRequestDTO",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def ipcch_ipcch_and_equivalent_most_recent_get_with_http_info(
        self,
        iso3: Optional[StrictStr] = None,
        page: Optional[StrictInt] = None,
        env: Annotated[
            Optional[StrictStr],
            Field(
                description="Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org"
            ),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[IpcchBaseDtoPagedResult]:
        """Retrieves a paginated list of the most recent IPCCH and Equivalent data, optionally filtered by ISO3 country code.

          ![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)  ![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)  ![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)  ### This endpoint is restricted, it requires the permission: \"vamdatabridges\\_ipcch-ipcchandequivalent-mostrecent\\_get\"      **Data Controller** - Wael ATTIA  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern

        :param iso3:
        :type iso3: str
        :param page:
        :type page: int
        :param env: Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
        :type env: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._ipcch_ipcch_and_equivalent_most_recent_get_serialize(
            iso3=iso3,
            page=page,
            env=env,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "IpcchBaseDtoPagedResult",
            "400": "BadRequestDTO",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def ipcch_ipcch_and_equivalent_most_recent_get_without_preload_content(
        self,
        iso3: Optional[StrictStr] = None,
        page: Optional[StrictInt] = None,
        env: Annotated[
            Optional[StrictStr],
            Field(
                description="Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org"
            ),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Retrieves a paginated list of the most recent IPCCH and Equivalent data, optionally filtered by ISO3 country code.

          ![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)  ![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)  ![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)  ### This endpoint is restricted, it requires the permission: \"vamdatabridges\\_ipcch-ipcchandequivalent-mostrecent\\_get\"      **Data Controller** - Wael ATTIA  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern

        :param iso3:
        :type iso3: str
        :param page:
        :type page: int
        :param env: Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
        :type env: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._ipcch_ipcch_and_equivalent_most_recent_get_serialize(
            iso3=iso3,
            page=page,
            env=env,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "IpcchBaseDtoPagedResult",
            "400": "BadRequestDTO",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        return response_data.response

    def _ipcch_ipcch_and_equivalent_most_recent_get_serialize(
        self,
        iso3,
        page,
        env,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {}

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if iso3 is not None:

            _query_params.append(("iso3", iso3))

        if page is not None:

            _query_params.append(("page", page))

        if env is not None:

            _query_params.append(("env", env))

        # process the header parameters
        # process the form parameters
        # process the body parameter

        # set the HTTP header `Accept`
        if "Accept" not in _header_params:
            _header_params["Accept"] = self.api_client.select_header_accept(
                ["text/plain", "application/json", "text/json"]
            )

        # authentication setting
        _auth_settings: List[str] = ["default"]

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/Ipcch/IPCCHAndEquivalent-MostRecent",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )

    @validate_call
    def ipcch_ipcch_and_equivalent_peaks_wfp_dashboard_get(
        self,
        iso3: Optional[StrictStr] = None,
        page: Annotated[
            Optional[StrictInt],
            Field(description="The page number for pagination. Defaults to 1."),
        ] = None,
        env: Annotated[
            Optional[StrictStr],
            Field(
                description="Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org"
            ),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> IpcchAndEquivalentPeaksDTOPagedResult:
        """Retrieves a paginated list of IPCCH and Equivalent Peaks data for the WFP Dashboard.

          ![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)  ![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)  ![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)  ### This endpoint is restricted, it requires the permission: \"vamdatabridges\\_ipcch-ipcchandequivalentpeakswfpdashboard\\_get\"      **Data Controller** - Wael ATTIA  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern

        :param iso3:
        :type iso3: str
        :param page: The page number for pagination. Defaults to 1.
        :type page: int
        :param env: Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
        :type env: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._ipcch_ipcch_and_equivalent_peaks_wfp_dashboard_get_serialize(
            iso3=iso3,
            page=page,
            env=env,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "IpcchAndEquivalentPeaksDTOPagedResult",
            "400": "BadRequestDTO",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def ipcch_ipcch_and_equivalent_peaks_wfp_dashboard_get_with_http_info(
        self,
        iso3: Optional[StrictStr] = None,
        page: Annotated[
            Optional[StrictInt],
            Field(description="The page number for pagination. Defaults to 1."),
        ] = None,
        env: Annotated[
            Optional[StrictStr],
            Field(
                description="Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org"
            ),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[IpcchAndEquivalentPeaksDTOPagedResult]:
        """Retrieves a paginated list of IPCCH and Equivalent Peaks data for the WFP Dashboard.

          ![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)  ![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)  ![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)  ### This endpoint is restricted, it requires the permission: \"vamdatabridges\\_ipcch-ipcchandequivalentpeakswfpdashboard\\_get\"      **Data Controller** - Wael ATTIA  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern

        :param iso3:
        :type iso3: str
        :param page: The page number for pagination. Defaults to 1.
        :type page: int
        :param env: Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
        :type env: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._ipcch_ipcch_and_equivalent_peaks_wfp_dashboard_get_serialize(
            iso3=iso3,
            page=page,
            env=env,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "IpcchAndEquivalentPeaksDTOPagedResult",
            "400": "BadRequestDTO",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def ipcch_ipcch_and_equivalent_peaks_wfp_dashboard_get_without_preload_content(
        self,
        iso3: Optional[StrictStr] = None,
        page: Annotated[
            Optional[StrictInt],
            Field(description="The page number for pagination. Defaults to 1."),
        ] = None,
        env: Annotated[
            Optional[StrictStr],
            Field(
                description="Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org"
            ),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Retrieves a paginated list of IPCCH and Equivalent Peaks data for the WFP Dashboard.

          ![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)  ![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)  ![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)  ### This endpoint is restricted, it requires the permission: \"vamdatabridges\\_ipcch-ipcchandequivalentpeakswfpdashboard\\_get\"      **Data Controller** - Wael ATTIA  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern

        :param iso3:
        :type iso3: str
        :param page: The page number for pagination. Defaults to 1.
        :type page: int
        :param env: Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
        :type env: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._ipcch_ipcch_and_equivalent_peaks_wfp_dashboard_get_serialize(
            iso3=iso3,
            page=page,
            env=env,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "IpcchAndEquivalentPeaksDTOPagedResult",
            "400": "BadRequestDTO",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        return response_data.response

    def _ipcch_ipcch_and_equivalent_peaks_wfp_dashboard_get_serialize(
        self,
        iso3,
        page,
        env,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {}

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if iso3 is not None:

            _query_params.append(("iso3", iso3))

        if page is not None:

            _query_params.append(("page", page))

        if env is not None:

            _query_params.append(("env", env))

        # process the header parameters
        # process the form parameters
        # process the body parameter

        # set the HTTP header `Accept`
        if "Accept" not in _header_params:
            _header_params["Accept"] = self.api_client.select_header_accept(
                ["text/plain", "application/json", "text/json"]
            )

        # authentication setting
        _auth_settings: List[str] = ["default"]

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/Ipcch/IPCCHAndEquivalentPeaks-WFPDashboard",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )

    @validate_call
    def ipcch_ipcch_historical_data_get(
        self,
        from_date: Annotated[
            Optional[datetime],
            Field(
                description="Date in the format yyyy-mm-dd, refers to the analysis date"
            ),
        ] = None,
        to_date: Annotated[
            Optional[datetime],
            Field(
                description="Date in the format yyyy-mm-dd, refers to the analysis date"
            ),
        ] = None,
        iso3: Optional[StrictStr] = None,
        page: Optional[StrictInt] = None,
        env: Annotated[
            Optional[StrictStr],
            Field(
                description="Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org"
            ),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> IpcHistoricalDatumDtoPagedResult:
        """Retrieves a paginated list of IPCCH and Equivalent Historical Data.

          ![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)  ![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)  ![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)  ### This endpoint is restricted, it requires the permission: \"vamdatabridges\\_ipcch-ipcch-historicaldata\\_get\"      **Data Controller** - Wael ATTIA  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern

        :param from_date: Date in the format yyyy-mm-dd, refers to the analysis date
        :type from_date: datetime
        :param to_date: Date in the format yyyy-mm-dd, refers to the analysis date
        :type to_date: datetime
        :param iso3:
        :type iso3: str
        :param page:
        :type page: int
        :param env: Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
        :type env: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._ipcch_ipcch_historical_data_get_serialize(
            from_date=from_date,
            to_date=to_date,
            iso3=iso3,
            page=page,
            env=env,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "IpcHistoricalDatumDtoPagedResult",
            "400": "BadRequestDTO",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def ipcch_ipcch_historical_data_get_with_http_info(
        self,
        from_date: Annotated[
            Optional[datetime],
            Field(
                description="Date in the format yyyy-mm-dd, refers to the analysis date"
            ),
        ] = None,
        to_date: Annotated[
            Optional[datetime],
            Field(
                description="Date in the format yyyy-mm-dd, refers to the analysis date"
            ),
        ] = None,
        iso3: Optional[StrictStr] = None,
        page: Optional[StrictInt] = None,
        env: Annotated[
            Optional[StrictStr],
            Field(
                description="Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org"
            ),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[IpcHistoricalDatumDtoPagedResult]:
        """Retrieves a paginated list of IPCCH and Equivalent Historical Data.

          ![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)  ![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)  ![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)  ### This endpoint is restricted, it requires the permission: \"vamdatabridges\\_ipcch-ipcch-historicaldata\\_get\"      **Data Controller** - Wael ATTIA  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern

        :param from_date: Date in the format yyyy-mm-dd, refers to the analysis date
        :type from_date: datetime
        :param to_date: Date in the format yyyy-mm-dd, refers to the analysis date
        :type to_date: datetime
        :param iso3:
        :type iso3: str
        :param page:
        :type page: int
        :param env: Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
        :type env: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._ipcch_ipcch_historical_data_get_serialize(
            from_date=from_date,
            to_date=to_date,
            iso3=iso3,
            page=page,
            env=env,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "IpcHistoricalDatumDtoPagedResult",
            "400": "BadRequestDTO",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def ipcch_ipcch_historical_data_get_without_preload_content(
        self,
        from_date: Annotated[
            Optional[datetime],
            Field(
                description="Date in the format yyyy-mm-dd, refers to the analysis date"
            ),
        ] = None,
        to_date: Annotated[
            Optional[datetime],
            Field(
                description="Date in the format yyyy-mm-dd, refers to the analysis date"
            ),
        ] = None,
        iso3: Optional[StrictStr] = None,
        page: Optional[StrictInt] = None,
        env: Annotated[
            Optional[StrictStr],
            Field(
                description="Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org"
            ),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Retrieves a paginated list of IPCCH and Equivalent Historical Data.

          ![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)  ![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)  ![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)  ### This endpoint is restricted, it requires the permission: \"vamdatabridges\\_ipcch-ipcch-historicaldata\\_get\"      **Data Controller** - Wael ATTIA  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern

        :param from_date: Date in the format yyyy-mm-dd, refers to the analysis date
        :type from_date: datetime
        :param to_date: Date in the format yyyy-mm-dd, refers to the analysis date
        :type to_date: datetime
        :param iso3:
        :type iso3: str
        :param page:
        :type page: int
        :param env: Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
        :type env: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._ipcch_ipcch_historical_data_get_serialize(
            from_date=from_date,
            to_date=to_date,
            iso3=iso3,
            page=page,
            env=env,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "IpcHistoricalDatumDtoPagedResult",
            "400": "BadRequestDTO",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        return response_data.response

    def _ipcch_ipcch_historical_data_get_serialize(
        self,
        from_date,
        to_date,
        iso3,
        page,
        env,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {}

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if from_date is not None:
            if isinstance(from_date, datetime):
                _query_params.append(
                    (
                        "fromDate",
                        from_date.strftime(
                            self.api_client.configuration.datetime_format
                        ),
                    )
                )
            else:
                _query_params.append(("fromDate", from_date))

        if to_date is not None:
            if isinstance(to_date, datetime):
                _query_params.append(
                    (
                        "toDate",
                        to_date.strftime(self.api_client.configuration.datetime_format),
                    )
                )
            else:
                _query_params.append(("toDate", to_date))

        if iso3 is not None:

            _query_params.append(("iso3", iso3))

        if page is not None:

            _query_params.append(("page", page))

        if env is not None:

            _query_params.append(("env", env))

        # process the header parameters
        # process the form parameters
        # process the body parameter

        # set the HTTP header `Accept`
        if "Accept" not in _header_params:
            _header_params["Accept"] = self.api_client.select_header_accept(
                ["text/plain", "application/json", "text/json"]
            )

        # authentication setting
        _auth_settings: List[str] = ["default"]

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/Ipcch/IPCCH-HistoricalData",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )
